language: go
go:
- 1.11.x
script:
- make lint
- make citest
after_script:
- curl -X POST https://pixe.la/v1/users/pi/webhooks/$CI_WEBHOOK_HASH -H 'Content-Length:0'
env:
  global:
    PIXELA_API_BASE='pixela.example.com'
    PIXELA_USER_TOKEN='thisissecret'
